/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Empresa;
import org.openapitools.client.model.Tutor;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Alumno
 */
public class AlumnoTest {
    private final Alumno model = new Alumno();

    /**
     * Model tests for Alumno
     */
    @Test
    public void testAlumno() {
        // TODO: test Alumno
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombreCompleto'
     */
    @Test
    public void nombreCompletoTest() {
        // TODO: test nombreCompleto
    }

    /**
     * Test the property 'ciclo'
     */
    @Test
    public void cicloTest() {
        // TODO: test ciclo
    }

    /**
     * Test the property 'evaluación'
     */
    @Test
    public void evaluaciónTest() {
        // TODO: test evaluación
    }

    /**
     * Test the property 'año'
     */
    @Test
    public void añoTest() {
        // TODO: test año
    }

    /**
     * Test the property 'tutor'
     */
    @Test
    public void tutorTest() {
        // TODO: test tutor
    }

    /**
     * Test the property 'empresa'
     */
    @Test
    public void empresaTest() {
        // TODO: test empresa
    }

}
