/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Usuario
 */
public class UsuarioTest {
    private final Usuario model = new Usuario();

    /**
     * Model tests for Usuario
     */
    @Test
    public void testUsuario() {
        // TODO: test Usuario
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombreUsuario'
     */
    @Test
    public void nombreUsuarioTest() {
        // TODO: test nombreUsuario
    }

    /**
     * Test the property 'contraseña'
     */
    @Test
    public void contraseñaTest() {
        // TODO: test contraseña
    }

    /**
     * Test the property 'tipo'
     */
    @Test
    public void tipoTest() {
        // TODO: test tipo
    }

    /**
     * Test the property 'idPerfil'
     */
    @Test
    public void idPerfilTest() {
        // TODO: test idPerfil
    }

    /**
     * Test the property 'activo'
     */
    @Test
    public void activoTest() {
        // TODO: test activo
    }

}
